# Generated by Django 5.2 on 2025-04-27 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_order_ordered_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('AP', 'All Products'), ('W', 'Women'), ('M', 'Men'), ('B', 'Bag'), ('S', 'Shoes'), ('WT', 'Watches')], default='AP', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='label',
            field=models.CharField(choices=[('P', 'primary'), ('S', 'secondary'), ('D', 'danger')], default='P', max_length=1),
            preserve_default=False,
        ),
    ]
